[versions]
indra = "3.1.3"
spotless = "6.22.0"
stylecheck = "0.2.1"
checkstyle = "10.12.3"

paper = "1.21.1-R0.1-SNAPSHOT"
jdbi = "3.45.4"
guice = "7.0.0"
command = "0.7.2"
hikari = "5.1.0"

[libraries]
build-indra = { group = "net.kyori", name = "indra-common", version.ref = "indra" }
build-spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
stylecheck = { group = "ca.stellardrift", name = "stylecheck", version.ref = "stylecheck" }

paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
jdbi = { group = "org.jdbi", name = "jdbi3-core", version.ref = "jdbi" }
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
command = { group = "team.unnamed", name = "commandflow-bukkit-commandmap", version.ref = "command" }
hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }
